--Insert Lookup Tables
--Power Rangers
--6/28/21

USE RV_HillAirForceBase

DELETE FROM DOD_AFFILIATION_TYPE;
DBCC CHECKIDENT ('DOD_AFFILIATION_TYPE', RESEED, 1)

GO
-- Insert rows into table 'DOD_AFFILIATION_TYPE'
INSERT INTO DOD_AFFILIATION_TYPE
(
 [DODAffilationType]
)
VALUES ('Army'), ('Air Force'), ('Navy'), ('Marines'), ('Coast Guard')

GO


DELETE FROM SERVICE_STATUS_TYPE;
DBCC CHECKIDENT ('SERVICE_STATUS_TYPE', RESEED, 1)

GO
-- Insert rows into table 'SERVICE_STATUS_TYPE'
INSERT INTO SERVICE_STATUS_TYPE
(
 [ServiceStatusType]
)
VALUES ('Active'), ('Retired'), ('Reserves'), ('PCS')

GO


DELETE FROM PAYMENT_REASON;
DBCC CHECKIDENT ('PAYMENT_REASON', RESEED, 1)

GO
-- Insert rows into table 'PAYMENT_REASON'
INSERT INTO PAYMENT_REASON
(
 [PayReasonName]
)
VALUES ('Reservation Payment'), ('Damage'), ('Violation')

GO


DELETE FROM PAYMENT_TYPE;
DBCC CHECKIDENT ('PAYMENT_TYPE', RESEED, 1)

GO
-- Insert rows into table 'PAYMENT_TYPE'
INSERT INTO PAYMENT_TYPE
(
 [PayType]
)
VALUES ('Card'), ('Cash'), ('Check')

GO


DELETE FROM RESERVATION_STATUS;
DBCC CHECKIDENT ('RESERVATION_STATUS', RESEED, 1)

GO 
-- Insert rows into table 'RESERVATION_STATUS'
INSERT INTO RESERVATION_STATUS
(
 [ResStatusName]
)
VALUES ('Scheduled'), ('Cancelled'), ('Completed')

GO

INSERT INTO RESERVATION_STATUS
(
 [ResStatusName], [ResStatusDescription]
)
VALUES ('Ongoing', 'Customer is expected to be on the campsite now.')

GO


DELETE FROM VEHICLE_TYPE;
DBCC CHECKIDENT ('VEHICLE_TYPE', RESEED, 1)

GO

-- Insert rows into table 'VEHICLE_TYPE'
INSERT INTO VEHICLE_TYPE
(
 [TypeName]
)
VALUES ('Motor Home'), ('Travel Trailer'), ('5th Wheel'), ('Pop Up')

GO

INSERT INTO VEHICLE_TYPE
(
 [TypeName], [TypeDescription]
)
VALUES ('Van', 'Preferred vehicle for living down by a river')

GO

INSERT INTO VEHICLE_TYPE
(
 [TypeName]
)
VALUES ('Other')

GO

--------------------------
-- Bult Insert Data Part 1 (TLA)
--------------------------

DECLARE @RelDir nvarchar(150)
DECLARE @tempFilePath nvarchar(200)

---UPDATE FILE PATH TO PATH WHERE FILES ARE LOCATED

BULK INSERT LOCATION FROM 'C:\BatchUpload\Location_1.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT SECURITY_QUESTION FROM 'C:\BatchUpload\SeqQuestion_1.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

--temp table here
BULK INSERT SPECIAL_EVENT FROM 'C:\BatchUpload\SpecialEvent_1.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT SITE_CATEGORY FROM 'C:\BatchUpload\SiteCategory_1.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT SITE_RATE FROM 'C:\BatchUpload\Site_Rate.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

--temp table here
BULK INSERT SITE FROM 'C:\BatchUpload\Site_1.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT CUSTOMER FROM 'C:\BatchUpload\Customer_1.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT SECURITY_ANSWER FROM 'C:\BatchUpload\SecurityAnswer_1.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT CUSTOMER_PASSWORD FROM 'C:\BatchUpload\CustPassword_1.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT RESERVATION FROM 'C:\BatchUpload\Reservation_1.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT PAYMENT FROM 'C:\BatchUpload\Payment_1.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

--------------------------
--Insert Data Part 2 (BAC)
--------------------------

--Same idea about updating the file paths that was mentioned by Tif above as well as the temp tables

BULK INSERT LOCATION FROM 'C:\BatchUpload\Location_2.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT SECURITY_QUESTION FROM 'C:\BatchUpload\SeqQuestion_2.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT SPECIAL_EVENT FROM 'C:\BatchUpload\SpecialEvent_2.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT SITE_CATEGORY FROM 'C:\BatchUpload\SiteCategory_2.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT SITE_RATE FROM 'C:\BatchUpload\Site_Rate_2.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT SITE FROM 'C:\BatchUpload\Site_2.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT CUSTOMER FROM 'C:\BatchUpload\Customer_2.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT SECURITY_ANSWER FROM 'C:\BatchUpload\SecurityAnswer_2.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT CUSTOMER_PASSWORD FROM 'C:\BatchUpload\CustPassword_2.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT RESERVATION FROM 'C:\BatchUpload\Reservation_2.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

BULK INSERT PAYMENT FROM 'C:\BatchUpload\Payment_2.txt'
WITH (FIELDTERMINATOR='|', FIRSTROW=2)

--Select statements Tif wrote to show all of the data in each table:

SELECT * FROM CUSTOMER
SELECT * FROM CUSTOMER_PASSWORD
SELECT * FROM DOD_AFFILIATION_TYPE
SELECT * FROM LOCATION
SELECT * FROM PAYMENT
SELECT * FROM PAYMENT_REASON
SELECT * FROM PAYMENT_TYPE
SELECT * FROM RESERVATION
SELECT * FROM RESERVATION_STATUS
SELECT * FROM SECURITY_ANSWER
SELECT * FROM SECURITY_QUESTION
SELECT * FROM SERVICE_STATUS_TYPE
SELECT * FROM SITE
SELECT * FROM SITE_CATEGORY
SELECT * FROM SITE_RATE
SELECT * FROM SPECIAL_EVENT
SELECT * FROM VEHICLE_TYPE